<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-O2SPC5C9" failures="1" tests="10" name="FullFlowTest" time="2.529" errors="0" timestamp="2025-07-29T12:15:54 IST">
  <testcase classname="com.api.tests.LoginTest" name="testValidLoginAPI" time="0.032"/>
  <testcase classname="com.api.tests.LoginTest" name="testInValidLoginAPI" time="0.018"/>
  <testcase classname="com.api.tests.UsersListTesting" name="testUsersListWithToken" time="0.101"/>
  <testcase classname="com.api.tests.UsersListTesting" name="testUsersListWithOutToken" time="0.018"/>
  <testcase classname="com.api.tests.UserCreationTest" name="testCreateUserWithToken" time="0.094"/>
  <testcase classname="com.api.tests.UserCreationTest" name="testCreateUserWithOutToken" time="0.018"/>
  <testcase classname="com.api.tests.UserUpdationTest" name="testUpdateUserWithToken" time="0.045"/>
  <testcase classname="com.api.tests.UserUpdationTest" name="testUpdateUserWithOutIdPassed" time="0.02"/>
  <testcase classname="com.api.tests.UserDeletionTest" name="testDeleteUserWithToken" time="0.016"/>
  <testcase classname="com.api.tests.UserDeletionTest" name="testDeleteUserWithWrongId" time="0.038">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;403&amp;gt; but was &amp;lt;200&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <403> but was <200>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at com.api.tests.UserDeletionTest.testDeleteUserWithWrongId(UserDeletionTest.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserWithWrongId -->
</testsuite> <!-- FullFlowTest -->
